# Generated by Django 3.1.4 on 2020-12-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='user/tesseract/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
